---
title: "axis_rotation"
author: "Ryan Yan"
date: "2023-04-07"
output: html_document
---
```{r}
source(here::here("load_libraries.R"))
```

```{r set up}
theme_set(theme_bw() + #set the theme 
            theme(text = element_text(family = "Times",size = 12))) #set the default text size
purpleOrange_palette6 = c("purple4","purple2","plum3","khaki","gold","goldenrod4")
purpleOrange_palette2 = c("purple4","gold")
```

```{r}
data_lm_anti <- read_csv("/Users/rh/Desktop/VRMID-analysis/data/data_lm_anticipation.csv")%>%
  select(-PosA_scaled, -NegA_scaled)

data_lm_outcome <- read_csv("/Users/rh/Desktop/VRMID-analysis/data/data_lm_outcome.csv")%>%
  select(-PosA_scaled, -NegA_scaled)%>%
  mutate(reaction_outcome = factor(reaction_outcome, levels = c("Hit","Miss")))
```

# Anticipation
## canonical axis: valence and arousal
```{r warning = F, message = F}
data_lm_anti$trial_type <- factor(data_lm_anti$trial_type, levels = c("-$5","-$1","-$0","+$0","+$1","+$5"))

lme1 <- lmer(scale(arousal_scaled) ~ scale(mean_pupil_baseline_ant) + (1|Subject) + (1|condition),
              data_lm_anti)
summary(lme1)

summary(lmer(mean_pupil_baseline_ant ~ arousal_scaled + valence_scaled + (1|Subject) + (1|condition),
              data_lm_anti))


p1 <- plot_model(lme1, type = "pred", terms = c("mean_pupil_baseline_ant"),
           show.data = T, dot.size = 0.5)+
  labs(title = "Anticipation arousal (collapsing cue types)")+
  xlim(-4,4)

lme2 <- lmer(valence_scaled ~ mean_pupil_baseline_ant + (1|Subject) + (1|condition),
              data_lm_anti)
summary(lme2)

p2 <- plot_model(lme2, type = "pred", terms = c("mean_pupil_baseline_ant"),
           show.data = T, dot.size = 0.5)+
  labs(title = "Anticipation valence (collapsing cue types)")+
  xlim(-4,4)

(p1+p2)

plot_model(lme1, type = "pred", terms = c("mean_pupil_baseline"),
           show.data = F)+
  labs(title = "Anticipation arousal")+
  scale_color_manual(values = purpleOrange_palette6)+
  scale_fill_manual(values = purpleOrange_palette6)+
  xlim(-4,4)+
plot_model(lme2, type = "pred", terms = c("mean_pupil_baseline"),
           show.data = F)+
  labs(title = "Anticipation valence")+
  scale_color_manual(values = purpleOrange_palette6)+
  scale_fill_manual(values = purpleOrange_palette6)+
  xlim(-4,4)
```

# axis rotation
## demonstration
```{r}
nbins = 4
angles = seq(0,pi/2, by = pi/(2*nbins))
angles = data.frame(angle1d = angles*180/pi,
                    angle1r = angles,
                    sin1 = sin(angles),
                    cos1 = cos(angles))

angles <- angles%>%
  mutate(angle2d = angle1d + 90,
         angle2r = angle1r + pi/2,
         sin2 = sin(angle2r),
         cos2 = cos(angle2r))

ggplot(angles)+
  geom_segment(aes(x = 0, y = 0, xend = cos1, yend = sin1, 
                   color = as.factor(angle1d)),
               size = 2, arrow = arrow(length = unit(0.1, "npc")))+
  geom_segment(aes(x = 0, y = 0, xend = cos2, yend = sin2, 
                   color = as.factor(angle1d)),
               size = 2, arrow = arrow(length = unit(0.1, "npc")))+
  geom_text(aes(label = "axis 1", x = cos1-0.1, y = sin1-0.2))+
  geom_text(aes(label = "axis 2", x = cos2+0.1, y = sin2-0.2))+
  facet_wrap(~angle1d)+
  scale_color_bluebrown_d()+
  xlim(-1,1)+
  ylim(-1,1)+
  labs(x = "valence", 
       y = "arousal",
       color = "angle (degree)")
```

```{r}
nbins = 100
angles = seq(0,pi/2, by = pi/(2*nbins))
angles = data.frame(angle1d = angles*180/pi,
                    angle1r = angles,
                    sin1 = sin(angles),
                    cos1 = cos(angles))

angles <- angles%>%
  mutate(angle2d = angle1d + 90,
         angle2r = angle1r + pi/2,
         sin2 = sin(angle2r),
         cos2 = cos(angle2r))

lmer_out1 <- {}

for (i in 1:nrow(angles)){
  angle_info = angles[i,]
  data_lm_anti_temp <- data_lm_anti%>%
    mutate(axis1 = valence_scaled * angle_info$cos1 + arousal_scaled * angle_info$sin1,
           axis2 = valence_scaled * angle_info$cos2 + arousal_scaled * angle_info$sin2)
  sum_temp1 <- summary(lmer(scale(axis1) ~ scale(mean_pupil_baseline) + (1|Subject) + (1|condition),
              data_lm_anti_temp))
  sum_temp2 <- summary(lmer(scale(axis2) ~ scale(mean_pupil_baseline) + (1|Subject) + (1|condition),
              data_lm_anti_temp))
  lmer_out1 <- rbind(lmer_out1, sum_temp1$coefficients[2,],sum_temp2$coefficients[2,])
}

lmer_out1 <- as.data.frame(lmer_out1)
lmer_out1$axis = rep(c("axis1","axis2"),nrow(angles))
  
lmer_out1[seq(1,nrow(angles)*2,by = 2),"angle"] = angles$angle1d
lmer_out1[seq(2,nrow(angles)*2,by = 2),"angle"] = angles$angle2d

lmer_out1$p_val <- (lmer_out1$`Pr(>|t|)` < 0.05)

ggplot(lmer_out1, aes(x = angle,
                     y = Estimate))+
  geom_line(aes(group = axis,
                linetype = axis))+
  geom_point(aes(color = p_val,
                 group = axis))+
  facet_wrap(~axis)+
  geom_hline(yintercept = 0)+
  labs(title = "axis correlation with pupil dilation during anticipation",
       subtitle = "angle is between axis and valence")+
  scale_color_manual(values = c("grey","maroon"))

a1 <- lmer_out1[which.max(abs(lmer_out1$Estimate)),]
```

## is this purely because of target motions?

```{r}
lmer_out <- {}

for (i in 1:nrow(angles)){
  angle_info = angles[i,]
  data_lm_anti_temp <- data_lm_anti%>%
    filter(condition == "large")%>%
    mutate(axis1 = valence_scaled * angle_info$cos1 + arousal_scaled * angle_info$sin1,
           axis2 = valence_scaled * angle_info$cos2 + arousal_scaled * angle_info$sin2)
  sum_temp1 <- summary(lmer(scale(axis1) ~ scale(mean_pupil_baseline) + (1|Subject),
              data_lm_anti_temp))
  sum_temp2 <- summary(lmer(scale(axis2) ~ scale(mean_pupil_baseline) + (1|Subject),
              data_lm_anti_temp))
  lmer_out <- rbind(lmer_out, sum_temp1$coefficients[2,],sum_temp2$coefficients[2,])
}

lmer_out <- as.data.frame(lmer_out)
lmer_out$axis = rep(c("axis1","axis2"),nrow(angles))
  
lmer_out[seq(1,nrow(angles)*2,by = 2),"angle"] = angles$angle1d
lmer_out[seq(2,nrow(angles)*2,by = 2),"angle"] = angles$angle2d

lmer_out$p_val <- (lmer_out$`Pr(>|t|)` < 0.05)

ggplot(lmer_out, aes(x = angle,
                     y = Estimate))+
  geom_line(aes(group = axis,
                linetype = axis))+
  geom_point(aes(color = p_val,
                 group = axis))+
  facet_wrap(~axis)+
  geom_hline(yintercept = 0)+
  labs(title = "axis correlation with pupil dilation during anticipation (large condition)",
       subtitle = "angle is between axis and valence")+
  scale_color_manual(values = c("grey","maroon"))
```
# outcome

```{r}
lme5 <- lmer(arousal_scaled ~ mean_pupil_baseline * reaction_outcome + (1|Subject) + (1|condition),
              data_lm_outcome)
summary(lme5)
p5 <- plot_model(lme5, type = "pred", terms = c("mean_pupil_baseline","reaction_outcome"),
           show.data = T)+
  labs(title = "Outcome Arous (collapsing cue types)",
       color = "Outcome")

lme5b <- lmer(mean_pupil_baseline ~ arousal_scaled * reaction_outcome + valence_scaled * reaction_outcome + (1|Subject) + (1|condition),data_lm_outcome)
summary(lme5b)
plot_model(lme5b, type = "pred", terms = c("arousal_scaled","reaction_outcome"),
           show.data = T)+
plot_model(lme5b, type = "pred", terms = c("valence_scaled","reaction_outcome"),
           show.data = T)

lme6 <- lmer(valence_scaled ~ mean_pupil_baseline * reaction_outcome + (1|Subject) + (1|condition),
              data_lm_outcome)
p6 <- plot_model(lme6, type = "pred", terms = c("mean_pupil_baseline","reaction_outcome"),
           show.data = T)+
  labs(title = "Outcome valence (collapsing cue types)",
       color = "Outcome")

p5+p6

```
```{r}
data_lm_outcome$reaction_outcome <- relevel(data_lm_outcome$reaction_outcome, ref = "Hit")

lmer_out2 <- {}

for (i in 1:nrow(angles)){
  angle_info = angles[i,]
  data_lm_out_temp <- data_lm_outcome%>%
    mutate(axis1 = valence_scaled * angle_info$cos1 + arousal_scaled * angle_info$sin1,
           axis2 = valence_scaled * angle_info$cos2 + arousal_scaled * angle_info$sin2)
  sum_temp1 <- summary(lmer(scale(axis1) ~ scale(mean_pupil_baseline) * reaction_outcome + (1|Subject) + (1|condition),
              data_lm_out_temp))
  sum_temp2 <- summary(lmer(scale(axis2) ~ scale(mean_pupil_baseline) * reaction_outcome + (1|Subject) + (1|condition),
              data_lm_out_temp))
  lmer_out2 <- rbind(lmer_out2, sum_temp1$coefficients[2,],sum_temp2$coefficients[2,])
}

lmer_out2 <- as.data.frame(lmer_out2)
lmer_out2$axis = rep(c("axis1","axis2"),nrow(angles))
  
lmer_out2[seq(1,nrow(angles)*2,by = 2),"angle"] = angles$angle1d
lmer_out2[seq(2,nrow(angles)*2,by = 2),"angle"] = angles$angle2d

lmer_out2$p_val <- (lmer_out2$`Pr(>|t|)` < 0.05)

ggplot(lmer_out2, aes(x = angle,
                     y = Estimate))+
  geom_line(aes(group = axis,
                linetype = axis))+
  geom_point(aes(color = p_val))+
  facet_wrap(~axis)+
  geom_hline(yintercept = 0)+
  labs(title = "axis correlation with pupil dilation during outcome - hit",
       subtitle = "angle is between axis and valence")+
  scale_color_manual(values = c("grey","maroon"))

a2 <- lmer_out2[which.max(abs(lmer_out2$Estimate)),]
```

```{r}
data_lm_outcome$reaction_outcome <- relevel(data_lm_outcome$reaction_outcome, ref = "Miss")

lmer_out3 <- {}

for (i in 1:nrow(angles)){
  angle_info = angles[i,]
  data_lm_out_temp <- data_lm_outcome%>%
    mutate(axis1 = valence_scaled * angle_info$cos1 + arousal_scaled * angle_info$sin1,
           axis2 = valence_scaled * angle_info$cos2 + arousal_scaled * angle_info$sin2)
  sum_temp1 <- summary(lmer(scale(axis1) ~ scale(mean_pupil_baseline) * reaction_outcome + (1|Subject) + (1|condition),
              data_lm_out_temp))
  sum_temp2 <- summary(lmer(scale(axis2) ~ scale(mean_pupil_baseline) * reaction_outcome + (1|Subject) + (1|condition),
              data_lm_out_temp))
  lmer_out3 <- rbind(lmer_out3, sum_temp1$coefficients[2,],sum_temp2$coefficients[2,])
}

lmer_out3 <- as.data.frame(lmer_out3)
lmer_out3$axis = rep(c("axis1","axis2"),nrow(angles))
  
lmer_out3[seq(1,nrow(angles)*2,by = 2),"angle"] = angles$angle1d
lmer_out3[seq(2,nrow(angles)*2,by = 2),"angle"] = angles$angle2d

lmer_out3$p_val <- (lmer_out3$`Pr(>|t|)` < 0.05)

ggplot(lmer_out3, aes(x = angle,
                     y = Estimate))+
  geom_line(aes(group = axis,
                linetype = axis))+
  geom_point(aes(color = p_val,
                 group = axis))+
  facet_wrap(~axis)+
  geom_hline(yintercept = 0)+
  labs(title = "axis correlation with pupil dilation during outcome - miss",
       subtitle = "angle is between axis and valence")+
  scale_color_manual(values = c("grey","maroon"))

a3 <- lmer_out3[which.max(abs(lmer_out3$Estimate)),]
```


```{r}
df_axes <- rbind(a1,a2,a3)
df_axes$condition <- c("anti","out-hit","out-miss")

df_axes <- df_axes%>%
  mutate(rad = angle/180 *pi,
         cos = cos(rad),
         sin = sin(rad))

ggplot(df_axes%>%
         mutate(cos = cos * abs(Estimate),
                sin = sin * abs(Estimate)))+
  geom_segment(aes(x = 0,y = 0,
                   xend = cos, yend = sin,
                   color = condition),
               size = 2, arrow = arrow(length = unit(0.03, "npc")))+
  geom_text(aes(x = 2*cos, y = 2*sin, color = condition, label = round(Estimate,2)))+
  scale_color_manual(values = c("gold","violet","purple"))+
  geom_segment(aes(x = -1, y = 0,
                   xend = 1, yend = 0),
               size = 0.5, arrow = arrow(length = unit(0.03, "npc")),
               color = "black")+
  geom_segment(aes(x = 0, y = -1,
                   xend = 0, yend = 1),
               size = 0.5, arrow = arrow(length = unit(0.03, "npc")),
               color = "black")+
    geom_segment(aes(x = -1, y = -1,
                   xend = 1, yend = 1),
               size = 0.5, linetype = "dashed",
               color = "black")+
    geom_segment(aes(x = -1, y = 1,
                   xend = 1, yend = -1),
               size = 0.5, linetype = "dashed",
               color = "black")+
  scale_color_manual(values = c("gold","violet","purple"))+
  xlim(-1,1)+
  ylim(-1,1)+
  labs(x = "valence",
       y = "arousal",
       title = "Association of self-report with pupil size (baseline corrected)",
       subtitle = "Standardised regression coefficients")
```



