---
title: "A8_occupation_affective_space"
author: "Ryan Yan"
date: "2023-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(lme4)
library(ggplot2)
library(lmerTest)
library(sjPlot)
library(patchwork)
library(see)
theme_set(theme_bw() + #set the theme 
            theme(text = element_text(family = "Helvetica",size = 12)))
purpleOrange_palette6 = c("purple4","purple2","plum3","gold","orange","goldenrod")
purpleOrange_palette2 = c("purple4","orange")
```

```{r}
data_lm_anti <- read_csv("/Users/rh/Desktop/VRMID-analysis/data/data_lm_anticipation.csv")%>%
  select(-PosA_scaled, -NegA_scaled)

data_lm_outcome <- read_csv("/Users/rh/Desktop/VRMID-analysis/data/data_lm_outcome.csv")%>%
  select(-PosA_scaled, -NegA_scaled)%>%
  mutate(reaction_outcome = factor(reaction_outcome, levels = c("Hit","Miss")))
```
# anticipation
```{r}
p1 <- ggplot(data_lm_anti, aes(x = valence, y = arousal))+
  geom_jitter(width = 0.1, height = 0.1,
              alpha = 0.1, color = "orange")+
  labs(title = "anticipation")

data_lm_anti <- data_lm_anti%>%
  mutate(valence_scaled_rounded = round(valence_scaled),
         arousal_scaled_rounded = round(arousal_scaled))
  
p3 <- ggplot(data_lm_anti, aes(x = valence_scaled, y = arousal_scaled))+
  geom_point(alpha = 0.5, color = "orange",size=1)+
  geom_smooth(method = "lm", formula = y~x+I(x^2),
              color = "black")+
  labs(title = "anticipation")

ggplot(data_lm_anti, aes(x = valence_scaled, y = arousal_scaled))+
  geom_jitter(width = 0.1, height = 0.1,
              alpha = 0.1, color = "orange")
```

# anticipation
```{r fig.width= 8, fig.height = 4}
p2 <- ggplot(data_lm_outcome, aes(x = valence, y = arousal,
                            color = reaction_outcome))+
  geom_jitter(width = 0.1, height = 0.1,
              alpha = 0.1)+
  facet_wrap(~reaction_outcome)+
  scale_color_bluebrown_d()+
  labs(title = "outcome")+
  theme(legend.position = "none")

data_lm_outcome <- data_lm_outcome%>%
  mutate(valence_scaled_rounded = round(valence_scaled),
         arousal_scaled_rounded = round(arousal_scaled))
  
ggplot(data_lm_outcome, aes(x = valence_scaled, y = arousal_scaled,
                            color = reaction_outcome))+
  geom_point(alpha = 0.5)+
  geom_smooth(method = "lm")+
  facet_wrap(~reaction_outcome)+
  scale_color_bluebrown_d()

p4 <- ggplot(data_lm_outcome, aes(x = valence_scaled, y = arousal_scaled,
                            color = reaction_outcome))+
  geom_point(alpha = 0.5)+
  geom_smooth(method = "lm")+
  geom_smooth(method = "lm", formula = y~x+I(x^2),color = "black")+
  scale_color_bluebrown_d()+
  labs(title = "outcome")+
  theme(legend.position = "right")+
  theme(legend.position = "none")
  

ggplot(data_lm_outcome, aes(x = valence_scaled_rounded, y = arousal_scaled_rounded,
                            color = reaction_outcome))+
  geom_jitter(width = 0.1, height = 0.1,
              alpha = 0.1)+
  facet_wrap(~reaction_outcome)+
  scale_color_bluebrown_d()
```

```{r}
p1+p2+p3+p4+
  plot_layout(nrow=2,widths =c(1,2))+ plot_annotation(tag_levels = 'A')
```


```{r}
lme0 <- lmer(scale(arousal_scaled) ~ scale(I(valence_scaled^2)) + scale(valence_scaled) +
               (1|Subject),data_lm_anti)
summary(lme0)

lme1 <- lmer(scale(arousal_scaled) ~ scale(valence_scaled) +
               (1|Subject),data_lm_outcome%>%
               filter(reaction_outcome == "Hit"))
summary(lme1)

lme2 <- lmer(scale(arousal_scaled) ~ scale(valence_scaled) +
               (1|Subject),data_lm_outcome%>%
               filter(reaction_outcome == "Miss"))
summary(lme2)
```

```{r}
modAA <- lmer(arousal_scaled ~ trial_type + (1|condition) + (1|Subject),data_lm_anti)

p1 <- plot_model(modAA, type = "pred", terms = "trial_type")+
  labs(title = "anticipation - arousal",
        x = "incentive value")+
  geom_line()+
  theme(legend.position = "none")

modAV <- lmer(valence_scaled ~ trial_type + (1|condition) + (1|Subject),data_lm_anti)

p2 <- plot_model(modAV, type = "pred", terms = "trial_type")+
  labs(title = "anticipation - valence",
        x = "incentive value")+
  geom_line()+
  theme(legend.position = "none")

modOA <- lmer(arousal_scaled ~ trial_type * reaction_outcome + (1|Subject) + (1|condition),data_lm_outcome)

p3 <- plot_model(modOA, type = "pred", terms = c("trial_type","reaction_outcome"))+
  labs(title = "outcome - arousal",
        x = "incentive value")+
  geom_line()+
  scale_color_bluebrown_d()+
  theme(legend.position = "none")


modOV <- lmer(valence_scaled ~ trial_type * reaction_outcome + (1|Subject) + (1|condition),data_lm_outcome)

p4 <-  plot_model(modOV, type = "pred", terms = c("trial_type","reaction_outcome"))+
  labs(title = "outcome - valence",
        x = "incentive value")+
  geom_line()+
  scale_color_bluebrown_d()+
  theme(legend.position = "none")

(p1+p2+p3+p4) +
  plot_layout(nrow = 1)+
  plot_annotation(tag_levels = "A")
```
