---
title: "A8_time_course_corr"
author: "Ryan Yan"
date: "2023-05-05"
output: html_document
---
```{r}
source(here::here("load_libraries.R"))
theme_set(theme_bw() + #set the theme 
            theme(text = element_text(family = "Helvetica",size = 12))) #set the default text size
```


```{r}
data_pupil <- read_csv("/Users/rh/Desktop/VRMID-analysis/data/pupillometry_lowpass_baselineCorrected.csv")%>%
  filter(!Subject %in% c("cn221206","vx220916"))%>% #bad participants
  # filter(condition %in% c("small","large"))%>%
  group_by(Subject)%>%
  mutate(arousal_scaled = as.numeric(scale(arousal)),
         valence_scaled = as.numeric(scale(valence)))

data_pupil$trial_type <- factor(data_pupil$trial_type, levels = c("-$5","-$1","-$0","+$0","+$1","+$5"))

data_pupil <- data_pupil%>%
  group_by(Subject)%>%
  mutate_at(vars(pupil_L,pupil_R,pupil_Avg,pupil_L_bc,pupil_R_bc,pupil_Avg_bc), 
            list(scale = scale))

#z-scoring

# names(data_pupil)
data_pupil <- data_pupil%>%
  mutate(sample_in_trial_t = round(sample_in_trial_t,4))

# calculate axis
data_pupil <- data_pupil%>%
  mutate(axis_affect = ifelse(probe == "anti",
                df_axes$cos[1] * valence_scaled + df_axes$sin[1] * arousal_scaled,
                ifelse(probe == "out" & reaction_outcome == "Hit",
                       df_axes$cos[2] * valence_scaled + df_axes$sin[2] * arousal_scaled,
                       ifelse(probe == "out" & reaction_outcome == "Miss",
                              df_axes$cos[3] * valence_scaled + df_axes$sin[3] * arousal_scaled,
                              NA))))
```

```{r warning = F, message=F}
regression_coefs_bc <- {}

for (t in 1:20) {
  coefs <- {}
  print(t)
  for (s in 1:120){
  df_ant_temp <- data_pupil%>%
  filter(probe == "anti",Time_sec == t, sample_in_sec == s)
  lm_ant_temp <- lmer(scale(axis_affect) ~ scale(pupil_Avg_bc_scale) + (1|Subject) + (1|condition),df_ant_temp)
  lm_out <- summary(lm_ant_temp)$coefficient[2,]
  coefs <- rbind(coefs,lm_out) 
  }
  coefs <- as.data.frame(coefs)%>%
    mutate(sample_in_sec = row_number(),
           Time_sec = t)
  rownames(coefs) <- NULL
  regression_coefs_bc <- rbind(regression_coefs_bc,coefs)
}

regression_coefs_bc <- regression_coefs_bc%>%
  mutate(sample_point = row_number(),
         p_val = (`Pr(>|t|)` < .001))
```

```{r warning = F, message=F}
regression_coefs_nobc <- {}

for (t in 1:20) {
  coefs <- {}
  print(t)
  for (s in 1:120){
  df_ant_temp <- data_pupil%>%
  filter(probe == "anti",Time_sec == t, sample_in_sec == s)
  lm_ant_temp <- lmer(scale(arousal_scaled) ~ scale(pupil_Avg_scale) + (1|Subject) + (1|condition),df_ant_temp)
  lm_out <- summary(lm_ant_temp)$coefficient[2,]
  coefs <- rbind(coefs,lm_out)
  }
  coefs <- as.data.frame(coefs)%>%
    mutate(sample_in_sec = row_number(),
           Time_sec = t)
  rownames(coefs) <- NULL
  regression_coefs_nobc <- rbind(regression_coefs_nobc,coefs)
}

regression_coefs_nobc <- regression_coefs_nobc%>%
  mutate(sample_point = row_number(),
         p_val = (`Pr(>|t|)` < .001))
```


```{r warning = FALSE, message=FALSE}
regression_coefs_out <- {}
data_pupil$reaction_outcome <- factor(data_pupil$reaction_outcome, levels = c("Hit","Miss"))

for (t in 1:20) {
  coefs <- {}
  print(t)
  for (s in 1:120){
  df_out_temp <- data_pupil%>%
  filter(probe == "out",Time_sec == t, sample_in_sec == s)
  lm_out_temp <- lmer(scale(axis_affect) ~ scale(pupil_Avg_bc_scale) + (1|Subject) + (1|condition),df_out_temp)
  lm_out <- summary(lm_out_temp)$coefficient[2,]
  coefs <- rbind(coefs,lm_out) 
  }
  coefs <- as.data.frame(coefs)%>%
    mutate(sample_in_sec = row_number(),
           Time_sec = t)
  rownames(coefs) <- NULL
  regression_coefs_out <- rbind(regression_coefs_out,coefs)
}

regression_coefs_out <- regression_coefs_out%>%
  mutate(sample_point = row_number(),
         p_val = (`Pr(>|t|)` < .001))
```

```{r warning = FALSE, message=FALSE}
regression_coefs_out_nobc <- {}
data_pupil$reaction_outcome <- factor(data_pupil$reaction_outcome, levels = c("Hit","Miss"))

for (t in 1:20) {
  coefs <- {}
  print(t)
  for (s in 1:120){
  df_out_temp <- data_pupil%>%
  filter(probe == "out",Time_sec == t, sample_in_sec == s)
  lm_out_temp <- lmer(scale(axis_affect) ~ scale(pupil_Avg_scale) + (1|Subject) + (1|condition),df_out_temp)
  lm_out <- summary(lm_out_temp)$coefficient[2,]
  coefs <- rbind(coefs,lm_out) 
  }
  coefs <- as.data.frame(coefs)%>%
    mutate(sample_in_sec = row_number(),
           Time_sec = t)
  rownames(coefs) <- NULL
  regression_coefs_out_nobc <- rbind(regression_coefs_out_nobc,coefs)
}

regression_coefs_out_nobc <- regression_coefs_out_nobc%>%
  mutate(sample_point = row_number(),
         p_val = (`Pr(>|t|)` < .001))
```



# permutation test
### helper functions
```{r}
get.adjacency.matrix <- function(x, threshold) {
  x <- ifelse(abs(x) > threshold, 1, 0)
  n <- length(x)
  adjacency_matrix <- matrix(0, n, n)
  for (i in 1:n) {
    for (j in (i+1):n) {
      if (x[i] == 1 & x[j] == 1) {
        adjacency_matrix[i,j] <- 1
        adjacency_matrix[j,i] <- 1
      }
    }
  }
  return(adjacency_matrix)
}
```

```{r}
# Define a function to calculate cluster-level p-values
get_cluster_p_values <- function(orig_cluster_size, num_permutations, t_values) {
  cluster_p_values <- numeric(length(orig_cluster_size))
  for (i in 1:num_permutations) {
    # permuted_t_values <- sign(runif(length(t_values), -1, 1)) * abs(t_values)
    permuted_t_values <- sample(t_values)
    permuted_adjacency_matrix <- (abs(permuted_t_values) > threshold)
    permuted_cluster <- get_cluster_sizes(permuted_adjacency_matrix, time)
    permuted_cluster_sizes <- permuted_cluster$cluster
    for (j in 1:length(orig_cluster_size)) {
      if (length(permuted_cluster_sizes) != 0){
        cluster_p_values[j] <- cluster_p_values[j] + (permuted_cluster_sizes >= orig_cluster_size[j])
      }
    }
  }
  cluster_p_values <- pmin(cluster_p_values / num_permutations, 1)
  return(cluster_p_values)
}
```

```{r}
# Define a function to calculate cluster sizes
get_cluster_sizes <- function(x,time) {
  cluster_indices <- cumsum(x)
  cluster_sizes <- tapply(cluster_indices, cluster_indices, length)
  cluster_sizes <- cluster_sizes[cluster_sizes >= cluster_extent_threshold & names(cluster_sizes) != 0]
  start_time <- c()
  end_time <- c()

  for (i in 1:length(cluster_sizes)){
    temp_time <- time[which(cluster_indices %in% names(cluster_sizes)[i])]
    start_time[i] <- min(temp_time)
    end_time[i] <- max(temp_time)
  }
  cluster_info <- list()
  cluster_info$cluster <- cluster_sizes
  cluster_info$start_time <- start_time
  cluster_info$end_time <- end_time
  return(cluster_info)
}
```

## anticipation
```{r warning = F, message=F}
# Define your data: t-values and beta estimates for each time point
t_values <- regression_coefs_bc$`t value`
time <- regression_coefs_bc$sample_point
beta_estimates <- regression_coefs_bc$Estimate

# Define your cluster-forming threshold (e.g. t-value of 2.0)
threshold <- 2.096

# Define your cluster extent threshold (e.g. minimum number of adjacent time points)
cluster_extent_threshold <- 240

# Get the adjacency matrix based on cluster-forming threshold
adjacency_matrix <- abs(t_values) < threshold

  # View(cbind(cluster_indices,time,adjacency_matrix))

orig_cluster <- get_cluster_sizes(adjacency_matrix,time)
orig_cluster_size <- orig_cluster$cluster

num_permutations <- 10000
cluster_threshold <- 0.05

cluster_p_values <- get_cluster_p_values(orig_cluster_size, 
                                         num_permutations, 
                                         t_values)

orig_cluster$start_time/120

for (c in 1:length(orig_cluster$cluster)) {
  start_time <- orig_cluster$start_time[c]
  end_time <- orig_cluster$end_time[c]
  cluster_size <- orig_cluster$cluster[c]
  print(paste("Cluster from", round(start_time/120,2), "ms to", round(end_time/120,2), "ms (", cluster_size, "time points) with p-value", cluster_p_values[c]))
}

d1 <- as.data.frame(cbind(orig_cluster$start_time,orig_cluster$end_time,cluster_p_values))
names(d1)[1:2] <- c("Start","End")
d1$Start/120
d1$End/120
```


```{r}
ant_bc_pupil <- data_pupil%>%
  filter(probe == "anti")%>%
  mutate(cluster = ifelse(sample_in_trial_n>= d1[1,1] & sample_in_trial_n <= d1[1,2],
                          "ant",
                          ifelse(sample_in_trial_n>= d1[2,1] & sample_in_trial_n <= d1[2,2],
                                 "out",NA)))%>%
  filter(cluster %in% c("ant","out"))%>%
  group_by(Subject,probe,cluster,condition,trial,arousal_scaled,valence_scaled)%>%
  summarise(mean_pupil_bc = mean(pupil_Avg_bc_scale,
                                 na.rm = T))%>%
  pivot_wider(names_from = "cluster", values_from = "mean_pupil_bc")

ant_bc_pupil$axis <- df_axes$cos[1] * ant_bc_pupil$valence_scaled + df_axes$sin[1] * ant_bc_pupil$arousal_scaled

summary(lmer(scale(out)~ scale(ant)+ (1|Subject) + (1|condition),ant_bc_pupil))

lma1 <- lmer(scale(axis) ~ scale(out) + (1|Subject) + (1|condition),ant_bc_pupil)
summary(lma1)

lma2 <- lmer(scale(axis) ~ scale(out) + scale(ant) + (1|Subject) + (1|condition),ant_bc_pupil)
summary(lma2)
```


```{r}
regression_coefs_bc <- regression_coefs_bc%>%
  mutate(significant_cluster = ifelse((sample_point >= d1[1,1] & sample_point <= d1[1,2]) |
                                      (sample_point >= d1[2,1] & sample_point <= d1[2,2]),"sig","ns"))

p1r <- ggplot(regression_coefs_bc, aes(x = sample_point, y = `t value`))+
  geom_point(aes(color = significant_cluster))+
  scale_color_bluebrown_d()+
  scale_x_continuous(breaks = c(0,600,1200,1800,2400),
                     labels = c(0,5,10,15,20))+
  labs(x = "sec",
       color = "sig. cluster",
       title = "anticipation probe")+
  # theme(legend.position = "bottom")+
  geom_hline(yintercept = 0, linetype = "dashed")+
  # annotate("rect", xmin = (0.1)*120, xmax = (4)*120, ymin = -3, ymax = 7.5,
  #          color = "lightseagreen", fill = NA)+
  # annotate("text", x = (2)*120,y = 0.18, label = "anticipation",
  #         color = "lightseagreen")+
  # annotate("rect", xmin =(4.1)*120, xmax = (6)*120, ymin = -3, ymax = 7.5,
  #         color = "lightskyblue1", fill = NA)+
  # annotate("text", x = (5)*120,y = 0.18, label = "fixation",
  #         color = "lightskyblue1")+
  # annotate("rect", xmin =(14.1)*120, xmax = (16)*120, ymin = -3, ymax = 7.5,
  #          color = "lightskyblue3", fill = NA)+
  # annotate("text", x = (15)*120,y = 0.18, label = "target",
  #         color = "lightskyblue3")+
  # annotate("rect", xmin = (16.1)*120, xmax = (18)*120, ymin = -3, ymax = 7.5,
  #          color = "lightskyblue4", fill = NA)+
  # annotate("text", x = (17)*120,y = 0.18, label = "outcome",
  #         color = "lightskyblue4")+
  geom_hline(yintercept = 2.096, color = "blue", linetype = "dashed")

p1l <- ggplot(df_axes[1,])+
  geom_segment(aes(x = 0, y = 0,xend = cos, yend = sin),
               arrow = arrow(length = unit(0.03, "npc")),
               color = "red")+
  xlim(-1,1)+
  ylim(-1,1)+
  labs(x = "valence", y = "arousal")+
  geom_segment(aes(x = -1, y = 0,
                   xend = 1, yend = 0),
               size = 0.5, arrow = arrow(length = unit(0.03, "npc")),
               color = "black")+
  geom_segment(aes(x = 0, y = -1,
                   xend = 0, yend = 1),
               size = 0.5, arrow = arrow(length = unit(0.03, "npc")),
               color = "black")+
    geom_segment(aes(x = -1, y = -1,
                   xend = 1, yend = 1),
               size = 0.5, linetype = "dashed",
               color = "black")+
    geom_segment(aes(x = -1, y = 1,
                   xend = 1, yend = -1),
               size = 0.5, linetype = "dashed",
               color = "black")
```


```{r}
data_pupil_summary_anticipation_collapse <- data_pupil%>%
  ungroup()%>%
  filter(probe == "anti",sample_in_trial_n <= 20*120)%>%
  group_by(sample_in_trial_n,sample_in_trial_t)%>%
  summarise(mean = mean(pupil_Avg_bc_scale, na.rm = T),
            lower = mean(pupil_Avg_bc_scale, na.rm = T) - qt(0.975, df = n() - 1) * sd(pupil_Avg_bc_scale, na.rm = T) / sqrt(n()),
            upper = mean(pupil_Avg_bc_scale, na.rm = T) + qt(0.975, df = n() - 1) * sd(pupil_Avg_bc_scale, na.rm = T) / sqrt(n()))%>%
  mutate(significant_cluster = ifelse((sample_in_trial_n >= d1[1,1] & sample_in_trial_n <= d1[1,2]) |
                                      (sample_in_trial_n >= d1[2,1] & sample_in_trial_n <= d1[2,2]),"sig","ns"))

p1b <- ggplot(data_pupil_summary_anticipation_collapse%>%
         filter(sample_in_trial_t <= 20), aes(x = sample_in_trial_t,
                       y = mean))+
  geom_point(aes(color = significant_cluster),
             size = 0.5)+
  geom_ribbon(aes(x = sample_in_trial_t,
                  ymin = lower, 
                  ymax = upper), 
              alpha = 0.2)+
  theme(legend.position = "right")+
  scale_color_viridis_d()+
  annotate("rect", xmin =0.1, xmax = 4, ymin = -1.5, ymax = 1.5,
           color = "lightseagreen", fill = NA)+
  annotate("text", x = 2,y = 1.2, label = "c",
          color = "lightseagreen")+
  annotate("rect", xmin =4.1, xmax = 6, ymin = -1.5, ymax = 1.5,
          color = "lightskyblue1", fill = NA)+
  annotate("text", x = 5,y = 1.2, label = "f",
          color = "lightskyblue1")+
  annotate("rect", xmin =14.1, xmax = 16, ymin = -1.5, ymax = 1.5,
           color = "lightskyblue3", fill = NA)+
  annotate("text", x = 15,y = 1.2, label = "t",
          color = "lightskyblue3")+
  annotate("rect", xmin = 16.1, xmax = 18, ymin = -1.5, ymax = 1.5,
           color = "lightskyblue4", fill = NA)+
  annotate("text", x = 17,y = 1.2, label = "o",
          color = "lightskyblue4")+
  # annotate("rect", xmin = 5.5, xmax = 7.5, ymin = -0.5, ymax = 0.5,
  #          color = "red", fill = "red", alpha = 0.1)+
  labs(title = "anticipation probe",
       subtitle = "significant cluster overlayed on phasic pupil",
       x = "time (s)",
       y = "z-scored pupil size")+
  geom_segment(aes(x = 12, y = 1, xend = 12, yend = 0.7),
                  arrow = arrow(length = unit(0.03, "npc")))+
  annotate("text",x = 12,y=1.2,label = "arousal report")
```

```{r fig.height= 6, fig.width= 8}
p1l + p1r + p1b+
  plot_layout(design = c(
  area(1,1),
  area(1,2,1,4),
  area(2,1,3,4)
))+ 
  plot_annotation(tag_levels = 'A')
```

# significant cluster stands after the previous cluster?
```{r}
my.df <- data_pupil%>%
  filter(probe == "anti")%>%
  mutate(significant_cluster = ifelse((sample_in_trial_n >= d1[1,1] & sample_in_trial_n <= d1[1,2]),"anti",
                                      ifelse(sample_in_trial_n >= d1[2,1] & sample_in_trial_n <= d1[2,2], "out",
                                            "ns")))%>%
  group_by(Subject,trial,trial_type,condition,probe,axis_affect,arousal_scaled, valence_scaled, significant_cluster)%>%
  summarise(pupil_Avg_bc_scale = mean(pupil_Avg_bc_scale,
                                      na.rm = T))%>%
  pivot_wider(names_from = significant_cluster,names_prefix = "pupil_", values_from = pupil_Avg_bc_scale)

l1 <- lmer(axis_affect ~ pupil_anti + (1|condition) + (1|Subject),my.df)
summary(l1)
l2 <- lmer(pupil_out ~ axis_affect + pupil_anti + (1|condition) + (1|Subject),my.df)
summary(l2)
```

## outcome
```{r warning = F, message=F}
# Define your data: t-values and beta estimates for each time point
t_values <- regression_coefs_out$`t value`
time <- regression_coefs_out$sample_point
beta_estimates <- regression_coefs_out$Estimate

# Define your cluster-forming threshold (e.g. t-value of 2.0)
threshold <- 2.096

# Define your cluster extent threshold (e.g. minimum number of adjacent time points)
cluster_extent_threshold <- 240

# Get the adjacency matrix based on cluster-forming threshold
adjacency_matrix <- abs(t_values) < threshold

  # View(cbind(cluster_indices,time,adjacency_matrix))

orig_cluster <- get_cluster_sizes(adjacency_matrix,time)
orig_cluster_size <- orig_cluster$cluster

num_permutations <- 10000
cluster_threshold <- 0.05

cluster_p_values <- get_cluster_p_values(orig_cluster_size, 
                                         num_permutations, 
                                         t_values)

orig_cluster$start_time/120

for (c in 1:length(orig_cluster$cluster)) {
  start_time <- orig_cluster$start_time[c]
  end_time <- orig_cluster$end_time[c]
  cluster_size <- orig_cluster$cluster[c]
  print(paste("Cluster from", round(start_time/120,2), "s to", round(end_time/120,2), "s (", cluster_size, "time points) with p-value", cluster_p_values[c]))
}

d2 <- as.data.frame(cbind(orig_cluster$start_time,orig_cluster$end_time,cluster_p_values))
names(d2)[1:2] <- c("Start","End")
d2
d2$Start/120
d2$End/120
```

```{r}
regression_coefs_out <- regression_coefs_out%>%
  mutate(significant_cluster = ifelse((sample_point >= d2[1,1] & sample_point <= d2[1,2]),"sig","ns"))

p2r <- ggplot(regression_coefs_out, aes(x = sample_point, y = `t value`))+
  geom_point(aes(color = significant_cluster))+
  scale_color_bluebrown_d()+
  scale_x_continuous(breaks = c(0,600,1200,1800,2400),
                     labels = c(0,5,10,15,20))+
  labs(x = "sec",
       color = "sig. cluster",
       title = "Outcome probe - hit")+
  # annotate("rect", xmin =(0.1)*120, xmax = (4)*120, ymin = -1.5, ymax = 6,
  #          alpha = .2, color = "lightseagreen", fill = NA)+
  # annotate("text", x = (2)*120,y = 1.2, label = "anticipation",
  #         color = "lightseagreen")+
  # annotate("rect", xmin =(4.1)*120, xmax = (6)*120, ymin = -1.5, ymax = 6,
  #          alpha = .2, color = "lightskyblue1", fill = NA)+
  # annotate("text", x = (5)*120,y = 1.2, label = "fixation",
  #         color = "lightskyblue1")+
  # annotate("rect", xmin = (6.1)*120, xmax = (8)*120, ymin = -1.5, ymax = 6,
  #          alpha = .2, color = "lightskyblue3", fill = NA)+
  # annotate("text", x = (7)*120,y = 1.2, label = "target",
  #         color = "lightskyblue3")+
  # annotate("rect", xmin = (8.1)*120, xmax = (10)*120, ymin = -1.5, ymax = 6,
  #          alpha = .2, color = "lightskyblue4", fill = NA)+
  # annotate("text", x = (9)*120,y = 1.2, label = "outcome",
  #         color = "lightskyblue4")+
  geom_hline(yintercept = 2.096, color = "blue", linetype = "dashed")

p2l <- ggplot(df_axes[2,])+
  geom_segment(aes(x = 0, y = 0,xend = cos, yend = sin),
               arrow = arrow(length = unit(0.03, "npc")),
               color = "red")+
  xlim(-1,1)+
  ylim(-1,1)+
  labs(x = "valence", y = "arousal")+
  geom_segment(aes(x = -1, y = 0,
                   xend = 1, yend = 0),
               size = 0.5, arrow = arrow(length = unit(0.03, "npc")),
               color = "black")+
  geom_segment(aes(x = 0, y = -1,
                   xend = 0, yend = 1),
               size = 0.5, arrow = arrow(length = unit(0.03, "npc")),
               color = "black")+
    geom_segment(aes(x = -1, y = -1,
                   xend = 1, yend = 1),
               size = 0.5, linetype = "dashed",
               color = "black")+
    geom_segment(aes(x = -1, y = 1,
                   xend = 1, yend = -1),
               size = 0.5, linetype = "dashed",
               color = "black")
```


```{r}
data_pupil_summary_outcome_collapse <- data_pupil%>%
  ungroup()%>%
  filter(probe == "out",sample_in_trial_n <= 20*120)%>%
  group_by(sample_in_trial_n,sample_in_trial_t)%>%
  summarise(mean = mean(pupil_Avg_bc_scale, na.rm = T),
            lower = mean(pupil_Avg_bc_scale, na.rm = T) - qt(0.975, df = n() - 1) * sd(pupil_Avg_bc_scale, na.rm = T) / sqrt(n()),
            upper = mean(pupil_Avg_bc_scale, na.rm = T) + qt(0.975, df = n() - 1) * sd(pupil_Avg_bc_scale, na.rm = T) / sqrt(n()))%>%
  mutate(significant_cluster = ifelse((sample_in_trial_n >= d2[1,1] & sample_in_trial_n <= d2[1,2]),"sig","ns"))

p2b <- ggplot(data_pupil_summary_outcome_collapse%>%
         filter(sample_in_trial_t <= 20), aes(x = sample_in_trial_t,
                       y = mean))+
  geom_point(aes(color = significant_cluster),
             size = 0.5)+
  geom_ribbon(aes(x = sample_in_trial_t,
                  ymin = lower, 
                  ymax = upper), 
              alpha = 0.2)+
  scale_color_viridis_d()+
  annotate("rect", xmin =0.1, xmax = 4, ymin = -1.5, ymax = 1.5,
           alpha = .2, color = "lightseagreen", fill = NA)+
  annotate("text", x = 2,y = 1.2, label = "c",
          color = "lightseagreen")+
  annotate("rect", xmin =4.1, xmax = 6, ymin = -1.5, ymax = 1.5,
           alpha = .2, color = "lightskyblue1", fill = NA)+
  annotate("text", x = 5,y = 1.2, label = "f",
          color = "lightskyblue1")+
  annotate("rect", xmin = 6.1, xmax = 8, ymin = -1.5, ymax = 1.5,
           alpha = .2, color = "lightskyblue3", fill = NA)+
  annotate("text", x = 7,y = 1.2, label = "t",
          color = "lightskyblue3")+
  annotate("rect", xmin = 8.1, xmax = 10, ymin = -1.5, ymax = 1.5,
           alpha = .2, color = "lightskyblue4", fill = NA)+
  # annotate("rect", xmin = 9.5, xmax = 11.5, ymin = -0.5, ymax = 0.5,
  #          color = "red", fill = "red", alpha = 0.1)+
  annotate("text", x = 9,y = 1.2, label = "o",
          color = "lightskyblue4")+
  labs(title = "Outcome probe",
       subtitle = "significant cluster overlayed on phasic pupil",
       x = "time (s)",
       y = "z-scored pupil size")+
  theme(legend.position = "none")+
  geom_segment(aes(x = 16, y = 1, xend = 16, yend = 0.7),
                  arrow = arrow(length = unit(0.03, "npc")))+
  annotate("text",x = 16,y=1.2,label = "arousal report")
```




```{r fig.width=8, fig.height=8}
p1b / p2b
```
#no bc bit
```{r}
p4a <- ggplot()+
  geom_point(data = regression_coefs_nobc, aes(x = sample_point, 
                                               y = `t value`,
                                               alpha = (`Pr(>|t|)` < .001), color = "anticipation"),
             size = 0.5)+
    scale_alpha_manual(values = c(0.05, 1))+
  scale_x_continuous(breaks = c(0,600,1200,1800,2400),
                     labels = c(0,5,10,15,20))+
  labs(x = "sec",
       alpha = "p < .001",
       title = "anticipation probe (full signal)",
       color = "trial type",
       y = "smooth t value")+
    scale_color_manual(values = c("orange","navy","skyblue"))+
  geom_hline(yintercept = 0, linetype = "dashed")+
  annotate("rect", xmin = 4*120, xmax = 6*120, ymin = -1, ymax = 15,
           alpha = .2, color = "orange", fill = NA, linetype = "dashed")+
  annotate("rect", xmin =16*120, xmax = 18*120, ymin = -1, ymax = 15,
           alpha = .2, color = "blue", fill = NA, linetype = "dashed")+
  annotate("text", x = 5*120, y = 10, color = "orange",label = "ant")+
  annotate("text", x = 17*120, y = 10, color = "blue",label = "out")+
  geom_segment(aes(x = 12*120, y = 15, xend = 12*120, yend = 13),
                  arrow = arrow(length = unit(0.03, "npc")))+
  annotate("text",x = 12*120,y=16,label = "arousal report")
  

p4b <- ggplot()+
  geom_point(data = regression_coefs_out_nobc, aes(x = sample_point, 
                                                   y = `t value`,
                                               alpha = (`Pr(>|t|)` < .001), color = "outcome"),
             size = 0.5)+
  scale_alpha_manual(values = c(1))+
  scale_x_continuous(breaks = c(0,600,1200,1800,2400),
                     labels = c(0,5,10,15,20))+
  labs(x = "sec",
       alpha = "p < .001",
       title = "outcome probe (full signal)",
       color = "trial type",
       y = "smooth t value")+
  scale_color_manual(values = c("skyblue"))+
  geom_hline(yintercept = 0, linetype = "dashed")+
  annotate("rect", xmin = 4*120, xmax = 6*120, ymin = -1, ymax = 15,
           alpha = .2, color = "orange", fill = NA, linetype = "dashed")+
  annotate("rect", xmin =8*120, xmax = 10*120, ymin = -1, ymax = 15,
           alpha = .2, color = "blue", fill = NA, linetype = "dashed")+
  annotate("text", x = 5*120, y = 10, color = "orange",label = "ant")+
  annotate("text", x = 9*120, y = 10, color = "blue",label = "out")+
  geom_segment(aes(x = 16*120, y = 12, xend = 16*120, yend = 9),
                  arrow = arrow(length = unit(0.03, "npc")))+
  annotate("text",x = 16*120,y=13,label = "arousal report")

```

```{r}
p5a <- ggplot()+
  geom_point(data = regression_coefs_bc, aes(x = sample_point, 
                                               y = `t value`,
                                             color = "anticipation",
                                             alpha = (`Pr(>|t|)` < .001)),
             size = 0.5)+
  scale_alpha_manual(values = c(0.05, 1))+
  scale_x_continuous(breaks = c(0,600,1200,1800,2400),
                     labels = c(0,5,10,15,20))+
  theme(legend.position = "none")+
  labs(x = "sec",
       alpha = "p < .001",
       title = "anticipation probe (phasic pupil)",
       color = "trial type",
       y = "smooth t value")+
    scale_color_manual(values = c("orange","navy","skyblue"))+
  geom_hline(yintercept = 0, linetype = "dashed")+
  annotate("rect", xmin = 4*120, xmax = 6*120, ymin = -1, ymax = 15,
           alpha = .2, color = "orange", fill = NA, linetype = "dashed")+
  annotate("rect", xmin =16*120, xmax = 18*120, ymin = -1, ymax = 15,
           alpha = .2, color = "blue", fill = NA, linetype = "dashed")+
  annotate("text", x = 5*120, y = 10, color = "orange",label = "ant")+
  annotate("text", x = 17*120, y = 10, color = "blue",label = "out")+
  geom_segment(aes(x = 12*120, y = 12, xend = 12*120, yend = 9),
                  arrow = arrow(length = unit(0.03, "npc")))+
  annotate("text",x = 12*120,y=13,label = "arousal report")
  

p5b <- ggplot()+
  geom_point(data = regression_coefs_out, aes(x = sample_point, 
                                                   y = `t value`,
                                               alpha = (`Pr(>|t|)` < .001), color = "out-hit"),
             size = 0.5)+
  theme(legend.position = "none")+
    scale_alpha_manual(values = c(0.05, 1))+
  scale_x_continuous(breaks = c(0,600,1200,1800,2400),
                     labels = c(0,5,10,15,20))+
  labs(x = "sec",
       alpha = "p < .001",
       title = "outcome probe (phasic pupil)",
       color = "trial type",
       y = "smooth t value")+
    scale_color_manual(values = c("skyblue"))+
  geom_hline(yintercept = 0, linetype = "dashed")+
  annotate("rect", xmin = 4*120, xmax = 6*120, ymin = -1, ymax = 15,
           alpha = .2, color = "orange", fill = NA, linetype = "dashed")+
  annotate("rect", xmin =8*120, xmax = 10*120, ymin = -1, ymax = 15,
           alpha = .2, color = "blue", fill = NA, linetype = "dashed")+
  annotate("text", x = 5*120, y = 10, color = "orange",label = "ant")+
  annotate("text", x = 9*120, y = 10, color = "blue",label = "out")+
  geom_segment(aes(x = 16*120, y = 12, xend = 16*120, yend = 9),
                  arrow = arrow(length = unit(0.03, "npc")))+
  annotate("text",x = 16*120,y=13,label = "arousal report")

theme_set(theme_bw() + #set the theme 
            theme(text = element_text(family = "Helvetica",size = 10)))

p4a+p4b + p5a+p5b+p1b+p2b+plot_annotation(tag_levels = "A")+
  plot_layout(nrow= 3)

p5a+p5b
p4a+p4b
```

